/**
 * Infrastructure Types for Generated Code
 */

/**
 * Bootstrap dependencies generated by smart generator
 */
export interface GeneratedBootstrapDependencies {
  imports: string[];
  setup: string[];
  cleanup: string[];
}

/**
 * Package dependencies analysis result
 */
export interface DependencyAnalysis {
  storage: Set<string>;
  cache: Set<string>;
  eventBus: Set<string>;
  queue: Set<string>;
  logger: Set<string>;
  transport: Set<string>;
  graphql: Set<string>;
  runtime: Set<string>;
}

/**
 * Infrastructure generation options
 */
export interface InfrastructureOptions {
  projectPath: string;
  useTypeScript: boolean;
  runtime: 'local' | 'docker' | 'kubernetes' | 'lambda';
}

/**
 * Docker infrastructure files
 */
export interface DockerInfrastructure {
  dockerfile: string;
  dockerCompose: string;
  dockerignore?: string;
}

/**
 * Kubernetes infrastructure files
 */
export interface KubernetesInfrastructure {
  deployment: string;
  service: string;
  configMap?: string;
  secrets?: string;
  ingress?: string;
}

/**
 * Lambda infrastructure files
 */
export interface LambdaInfrastructure {
  handler: string;
  serverless: string;
  buildSpec?: string;
}

/**
 * Generated infrastructure result
 */
export interface GeneratedInfrastructure {
  docker?: DockerInfrastructure;
  kubernetes?: KubernetesInfrastructure;
  lambda?: LambdaInfrastructure;
}

/**
 * Bootstrap generation result
 */
export interface BootstrapGenerationResult {
  bootstrapCode: string;
  dependencies: Record<string, string>;
  infrastructure?: GeneratedInfrastructure;
}
